project_name: alertmanager-controller
dist: releases
release:
  github:
    owner: ekristen
    name: alertmanager-controller
builds:
  - goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s
      - -X '{{ .ModulePath }}/pkg/common.SUMMARY=v{{ .Version }}'
      - -X '{{ .ModulePath }}/pkg/common.BRANCH={{ .Branch }}'
      - -X '{{ .ModulePath }}/pkg/common.VERSION={{ .Tag }}'
      - -X '{{ .ModulePath }}/pkg/common.COMMIT={{ .Commit }}'
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    image_templates:
      - ghcr.io/ekristen/alertmanager-controller:{{ .Version }}
      - ghcr.io/ekristen/alertmanager-controller:{{ replace .Branch "/" "-" }}-{{ .ShortCommit }}-{{ .Timestamp }}
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/ekristen/alertmanager-controller"
      - "--platform=linux/amd64"
signs:
  - cmd: cosign
    stdin: "{{ .Env.COSIGN_PASSWORD }}"
    args:
      - "sign-blob"
      - "--key=cosign.key"
      - "--output-signature=${signature}"
      - "${artifact}"
    artifacts: all
docker_signs:
  - artifacts: all
    stdin: "{{ .Env.COSIGN_PASSWORD }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Summary }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
