{{- range $configMapName, $configMap := .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configMapName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app_name: {{ $.Release.Name }}
    app_version: {{ $.Values.image.tag }}
    {{- with $configMap.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  {{- toYaml $configMap.data | nindent 2 }}
{{- end }}
