apiVersion: promam.ekristen.dev/v1
kind: Silence
metadata:
  name: testing
spec:
  startsAt: 2022-05-30T00:00:00Z
  endsAt: 2022-06-07T23:00:00Z
  createdBy: prom-am-operator
  comment: "automated silence"
  matchers:
    - name: blah
      value: bleh
      isRegex: false
      isEqual: true
